function [fitresult, gof] = createFit(N_3d, omega_3d)
%CREATEFIT(N_3D,OMEGA_3D)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : N_3d
%      Y Output: omega_3d
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 23-Apr-2020 12:06:04


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( N_3d, omega_3d );

% Set up fittype and options.
ft = fittype( '-a/x+b', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.StartPoint = [0.859871740379996 0.448754410406848];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'data', 'curve fit', 'Location', 'NorthEast', 'Interpreter', 'none' );
% Label axes
xlabel( 'N', 'Interpreter', 'none' );
ylabel( '\omega^2' );
grid on


